### ISSUE TITLE
minor type error

### ISSUE THREAD

**Issue by leecom3025** [intel-iot-devkit/upm#215] opened 2015-07-06 15:50 UTC
https://github.com/intel-iot-devkit/upm/blob/master/src/hcsr04/hcsr04.cxx
line 52, 
    gpio_edge_t edge = MRAA_GPIO_EDGE_BOTH;
should be 
    mraa_gpio_edge_t edge = MRAA_GPIO_EDGE_BOTH;

Please correct it.

**Comment by alext-mkrs** [comment] 2015-07-06 16:50
This is a duplicate of #214

**Closed** 2015-07-06 18:49 UTC
